name: firebrand-thermal
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - opencv-python-headless
      - numpy
      - pillow
      - customtkinter
      - darkdetect
      - click
      - pytest
      - netCDF4
      - pyinstaller
